### PR TITLE
Merge dev/rumble

### PR DESCRIPTION
**Pull request by Moeez-Muhammad**
This library is to allow easy rumbling of Xbox Controllers. The easiest
use case is that of notifying drivers of different events such as
value changes, warnings, etc. This library automatically rumbles with
the set intensity on the set side, then turns it off quickly to simulate
the rumbling in regular video games. Also, it can be run asynchronously
to not impede with the rest of the regular robot operations.

### CODE REVIEW

**Comment by tylertian123** [comment]
I like it, seems like a great idea! Personally though, I would encapsulate the `Executor` stuff and just make a static method. What do you think?

Also, a few more small suggestions. You're missing a space after `public class Rumble implements Runnable`. Other than that, if you take the block comment explaining what the class does, move it so it's just above the `public class Rumble implements Runnable` line and make it start with `/**` instead of `/*`, it will become a JavaDoc comment instead of a regular comment. With JavaDoc comments, you can see them just by hovering over the class name.

**Comment by Moeez-Muhammad** [comment]
Ok, thanks! I'll add the stuff you suggested.

**Comment by Moeez-Muhammad** [comment]
I encapsulated the ExecutorService, and I think it will work. I also didn't move the Javadoc, because in vscode, it would only show the parameters part if it was in the class Javadoc, not in the constructor one.

**Comment by tylertian123** [comment]
You'd have to hover over a call to the actual constructor for VS Code to show it. For example:
```java
//...
/**
 * A {@code Trigger} that monitors current on a PDP channel, activating when the maximum current has been exceeded for a period of time.
 */
public class CurrentMonitoringTrigger extends Trigger {

    int pdpChannel;
    double currentLimit;
    double overcurrentTime;
    //NaN represents the current limit was never exceeded
    double exceededAt = Double.NaN;

    boolean enabled = true;

    /**
     * Creates a new current monitoring trigger.
     * 
     * @param pdpChannel The PDP channel to monitor current from
     * @param currentLimit The maximum current limit, in amps
     * @param overcurrentTime The number of seconds of overcurrent allowed before this trigger becomes active
     */
    public CurrentMonitoringTrigger(int pdpChannel, double currentLimit, double overcurrentTime) {
        this.pdpChannel = pdpChannel;
        this.currentLimit = currentLimit;
        this.overcurrentTime = overcurrentTime;
    }
//...
```
In this example for `CurrentMonitoringTrigger`, there are JavaDoc entires for both the class itself, and the constructor. Thus,
```java
CurrentMonitoringTrigger trigger = new CurrentMonitoringTrigger(0, 20, 2);
```
When you hover over the first "CurrentMonitoringTrigger", which is a class type, it will display the JavaDoc associated with the class ("A {@code Trigger} that monitors current..."). When you hover over the second one, which is a call to the constructor, it will display the JavaDoc for the constructor instead ("Creates a new current monitoring trigger...").

**Comment by Moeez-Muhammad** [comment]
Oh ok, I get it now. Also, I got this error when I tried to commit directly to master to fix it. Do I have to open the pull request again?

```bash
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (9/9), 694 bytes | 0 bytes/s, done.
Total 9 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "Travis CI - Branch" is expected. At least 1 approving review is required by reviewers with write access.
To https://github.com/Arctos6135/frc-2019
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://Moeez-Muhammad@github.com/Arctos6135/frc-2019'
```

**Comment by tylertian123** [comment]
Oh yeah, that's normal. Yes, unfortunately, you do have to open another PR. I've set it up so that the master branch is protected, ie direct commits and merges to master are not allowed, unless through a PR with at least one review and all CI checks passing. 

There's a bit of work involved in fixing this. First, back up the new changes you've made in the commit you failed to push. Then run a `git reset --hard HEAD^1` on master, which undoes your last commit so your local master is now the same as the remote master. Then go back to dev/rumble and make whatever change you want to. Finally, push and resubmit another PR.

**Comment by tylertian123** [comment]
Hmm, hold on. I missed a mistake. Line 31, the supposed constructor, was declared like this:
```java
public void Rumble (XboxController controller, String side, float intensity) {
```
Which has a return type of `void`. Since constructors are defined with no return values, right now `Rumble.Rumble()` is simply another method. To make it the constructor, remove the `void`.

**Comment by Moeez-Muhammad** [comment]
Yeah, I realized that that was why the javadoc wasn't working, because it wasn't recognized as a constructor.

**Pull request merged**
