### PR TITLE
Dev/guest mode

### PR DESCRIPTION
**Pull request by Moeez-Muhammad**
All the fixes have been merged from dev/guest-mode-fixes, so this should be able to just merge cleanly and easily :+1:

### CODE REVIEW

**Comment by tylertian123** [comment]
Not sure if we want this on `master` just yet though... As it always is with code, there are a lot of things that could go wrong.

**Comment by Moeez-Muhammad** [comment]
How do we revert the merge?

**Comment by tylertian123** [comment]
I suggest keeping the `dev/guest-mode` branch for now so we can do some bug fixes with it in case the code doesn't work perfectly. It can be deleted after the dinner when we know that it works.

**Comment by tylertian123** [comment]
I mean, you could revert it, but since it's already been done it's fine lol.

**Comment by tylertian123** [comment]
Let's see how this goes. Most likely there won't be any problems. I was planning on playing it safe and refrain from merging until after the code's been tested, but now that it's already merged, I see little point in undoing it.

**Comment by squishybanana04** [comment]
If anything goes wrong just drop a fat git reset

**Comment by Moeez-Muhammad** [comment]
Factual

**Pull request merged**
