### PR TITLE
Fixes for dev/guest-mode

### PR DESCRIPTION
**Pull request by tylertian123**
Fix various issues with `dev/guest-mode`.

Summary:
* Move repeated code in `OI.java` outside of the `if` statement
* Create class `ConditionalButton` (extends `Button`), which wraps around a normal `Button` and can only be activated when a boolean is true
* Use `ConditionalButton`s to disable buttons in Guest Mode and buttons that are only active during Guest Mode, instead of reconstructing `OI`
* Various other changes to code style to maintain consistency

### CODE REVIEW

**Comment by tylertian123** [comment]
Some other changes to the controls have also been applied upon request.

**Comment by Moeez-Muhammad** [comment]
All the code from dev/guest-mode is in here, so we can merge this and delete dev/guest-mode right?

**Comment by Moeez-Muhammad** [comment]
NVM I forgot how git works for a second there.

**Comment by Moeez-Muhammad** [comment]
Ohh this was branched off of dev/guest-mode

**Pull request merged**
